"use strict";

var packageName = "andylash:intljs";

Npm.depends({
 "intl": "0.1.4"
});

var packageDir = 'meteor-intljs';
Package.describe({
  summary: "Meteor wrapper around Intl.js polyfill with some sugar around loading locale files",
  version: "0.1.1",
  name: packageName,
  git: "https://github.com/andylash/" + packageDir + ".git"
});

// //stole this from http://stackoverflow.com/questions/20793505/meteor-package-api-add-files-add-entire-folder
// function getFilesFromFolder(folder) {
//   // local imports
//   var _ = Npm.require("underscore");
//   var fs = Npm.require("fs");
//   var path = Npm.require("path");
//   // helper function, walks recursively inside nested folders and return absolute filenames
//   function walk(folder) {
//     var filenames = [];
//     // get relative filenames from folder
//     var folderContent = fs.readdirSync(folder);
//     // iterate over the folder content to handle nested folders
//     _.each(folderContent, function(filename) {
//       // build absolute filename
//       var absoluteFilename = folder + path.sep + filename;
//       // get file stats
//       var stat = fs.statSync(absoluteFilename);
//       if (stat.isDirectory()) {
//         // directory case => add filenames fetched from recursive call
//         filenames = filenames.concat(walk(absoluteFilename));
//       } else {
//         // file case => simply add it
//         filenames.push(absoluteFilename);
//       }
//     });
//     return filenames;
//   }

//   // // save current working directory (something like "/home/user/projects/my-project")
//   // var cwd = process.cwd();

//   // // chdir to our package directory
//   // process.chdir(folder);
//   // launch initial walk
//   var result = walk(folder);
//   // restore previous cwd
//   // process.chdir(cwd);
//   return result;
// }

Package.onUse(function(api) {
  api.versionsFrom('METEOR@0.9.4');
  api.use('http', 'client');

  //on the server load the complete that has all locales
  api.addFiles('src/npmIntl.js', 'server');

  //on the client load the minimum, locales load on demand
  api.addFiles('Intl.js/dist/Intl.js', 'client');

  //here we're exporting the variables
  api.addFiles('src/export.js', 'client');

  //here's the on demand loading part
  api.addFiles('src/loader.js', 'client');

  //Wasn't happy with this dynamic loading
  // var localeFiles = getFilesFromFolder(getFolder());

  // console.log("Adding files: " + localeFiles);
  api.addFiles(getLocaleFiles(), ['client'], {
    isAsset: true
  });

  //let's have at least something available on load
  api.addFiles('Intl.js/locale-data/jsonp/en-US.js', 'client');

  api.export(['Intl', 'IntlPolyfill']);
});

// var getFolder = function() {
//   var fs = Npm.require('fs');
//   var curDir = fs.realpathSync('.');

//   var packagesIndex = curDir.indexOf('/packages/');
//   if (packagesIndex > 0) {
//     curDir = curDir.slice(0, packagesIndex + 1);
//   }
//   var path = curDir + "packages/" + packageDir + "/Intl.js/locale-data/json";
//   console.log(path);
//   return path;
// };

var getLocaleFiles = function() {
  return [
"Intl.js/locale-data/json/aa-DJ.json",
"Intl.js/locale-data/json/aa-ER.json",
"Intl.js/locale-data/json/aa-ET.json",
"Intl.js/locale-data/json/aa.json",
"Intl.js/locale-data/json/af-NA.json",
"Intl.js/locale-data/json/af-ZA.json",
"Intl.js/locale-data/json/af.json",
"Intl.js/locale-data/json/agq-CM.json",
"Intl.js/locale-data/json/agq.json",
"Intl.js/locale-data/json/ak-GH.json",
"Intl.js/locale-data/json/ak.json",
"Intl.js/locale-data/json/am-ET.json",
"Intl.js/locale-data/json/am.json",
"Intl.js/locale-data/json/ar-001.json",
"Intl.js/locale-data/json/ar-AE.json",
"Intl.js/locale-data/json/ar-BH.json",
"Intl.js/locale-data/json/ar-DJ.json",
"Intl.js/locale-data/json/ar-DZ.json",
"Intl.js/locale-data/json/ar-EG.json",
"Intl.js/locale-data/json/ar-EH.json",
"Intl.js/locale-data/json/ar-ER.json",
"Intl.js/locale-data/json/ar-IL.json",
"Intl.js/locale-data/json/ar-IQ.json",
"Intl.js/locale-data/json/ar-JO.json",
"Intl.js/locale-data/json/ar-KM.json",
"Intl.js/locale-data/json/ar-KW.json",
"Intl.js/locale-data/json/ar-LB.json",
"Intl.js/locale-data/json/ar-LY.json",
"Intl.js/locale-data/json/ar-MA.json",
"Intl.js/locale-data/json/ar-MR.json",
"Intl.js/locale-data/json/ar-OM.json",
"Intl.js/locale-data/json/ar-PS.json",
"Intl.js/locale-data/json/ar-QA.json",
"Intl.js/locale-data/json/ar-SA.json",
"Intl.js/locale-data/json/ar-SD.json",
"Intl.js/locale-data/json/ar-SO.json",
"Intl.js/locale-data/json/ar-SS.json",
"Intl.js/locale-data/json/ar-SY.json",
"Intl.js/locale-data/json/ar-TD.json",
"Intl.js/locale-data/json/ar-TN.json",
"Intl.js/locale-data/json/ar-YE.json",
"Intl.js/locale-data/json/ar.json",
"Intl.js/locale-data/json/as-IN.json",
"Intl.js/locale-data/json/as.json",
"Intl.js/locale-data/json/asa-TZ.json",
"Intl.js/locale-data/json/asa.json",
"Intl.js/locale-data/json/ast-ES.json",
"Intl.js/locale-data/json/ast.json",
"Intl.js/locale-data/json/az-Cyrl-AZ.json",
"Intl.js/locale-data/json/az-Cyrl.json",
"Intl.js/locale-data/json/az-Latn-AZ.json",
"Intl.js/locale-data/json/az-Latn.json",
"Intl.js/locale-data/json/az.json",
"Intl.js/locale-data/json/bas-CM.json",
"Intl.js/locale-data/json/bas.json",
"Intl.js/locale-data/json/be-BY.json",
"Intl.js/locale-data/json/be.json",
"Intl.js/locale-data/json/bem-ZM.json",
"Intl.js/locale-data/json/bem.json",
"Intl.js/locale-data/json/bez-TZ.json",
"Intl.js/locale-data/json/bez.json",
"Intl.js/locale-data/json/bg-BG.json",
"Intl.js/locale-data/json/bg.json",
"Intl.js/locale-data/json/bm-Latn-ML.json",
"Intl.js/locale-data/json/bm-Latn.json",
"Intl.js/locale-data/json/bm-ML.json",
"Intl.js/locale-data/json/bm.json",
"Intl.js/locale-data/json/bn-BD.json",
"Intl.js/locale-data/json/bn-IN.json",
"Intl.js/locale-data/json/bn.json",
"Intl.js/locale-data/json/bo-CN.json",
"Intl.js/locale-data/json/bo-IN.json",
"Intl.js/locale-data/json/bo.json",
"Intl.js/locale-data/json/br-FR.json",
"Intl.js/locale-data/json/br.json",
"Intl.js/locale-data/json/brx-IN.json",
"Intl.js/locale-data/json/brx.json",
"Intl.js/locale-data/json/bs-Cyrl-BA.json",
"Intl.js/locale-data/json/bs-Cyrl.json",
"Intl.js/locale-data/json/bs-Latn-BA.json",
"Intl.js/locale-data/json/bs-Latn.json",
"Intl.js/locale-data/json/bs.json",
"Intl.js/locale-data/json/byn-ER.json",
"Intl.js/locale-data/json/byn.json",
"Intl.js/locale-data/json/ca-AD.json",
"Intl.js/locale-data/json/ca-ES-VALENCIA.json",
"Intl.js/locale-data/json/ca-ES.json",
"Intl.js/locale-data/json/ca-FR.json",
"Intl.js/locale-data/json/ca-IT.json",
"Intl.js/locale-data/json/ca.json",
"Intl.js/locale-data/json/cgg-UG.json",
"Intl.js/locale-data/json/cgg.json",
"Intl.js/locale-data/json/chr-US.json",
"Intl.js/locale-data/json/chr.json",
"Intl.js/locale-data/json/cs-CZ.json",
"Intl.js/locale-data/json/cs.json",
"Intl.js/locale-data/json/cy-GB.json",
"Intl.js/locale-data/json/cy.json",
"Intl.js/locale-data/json/da-DK.json",
"Intl.js/locale-data/json/da-GL.json",
"Intl.js/locale-data/json/da.json",
"Intl.js/locale-data/json/dav-KE.json",
"Intl.js/locale-data/json/dav.json",
"Intl.js/locale-data/json/de-AT.json",
"Intl.js/locale-data/json/de-BE.json",
"Intl.js/locale-data/json/de-CH.json",
"Intl.js/locale-data/json/de-DE.json",
"Intl.js/locale-data/json/de-LI.json",
"Intl.js/locale-data/json/de-LU.json",
"Intl.js/locale-data/json/de.json",
"Intl.js/locale-data/json/dje-NE.json",
"Intl.js/locale-data/json/dje.json",
"Intl.js/locale-data/json/dsb-DE.json",
"Intl.js/locale-data/json/dsb.json",
"Intl.js/locale-data/json/dua-CM.json",
"Intl.js/locale-data/json/dua.json",
"Intl.js/locale-data/json/dyo-SN.json",
"Intl.js/locale-data/json/dyo.json",
"Intl.js/locale-data/json/dz-BT.json",
"Intl.js/locale-data/json/dz.json",
"Intl.js/locale-data/json/ebu-KE.json",
"Intl.js/locale-data/json/ebu.json",
"Intl.js/locale-data/json/ee-GH.json",
"Intl.js/locale-data/json/ee-TG.json",
"Intl.js/locale-data/json/ee.json",
"Intl.js/locale-data/json/el-CY.json",
"Intl.js/locale-data/json/el-GR.json",
"Intl.js/locale-data/json/el.json",
"Intl.js/locale-data/json/en-001.json",
"Intl.js/locale-data/json/en-150.json",
"Intl.js/locale-data/json/en-AG.json",
"Intl.js/locale-data/json/en-AI.json",
"Intl.js/locale-data/json/en-AS.json",
"Intl.js/locale-data/json/en-AU.json",
"Intl.js/locale-data/json/en-BB.json",
"Intl.js/locale-data/json/en-BE.json",
"Intl.js/locale-data/json/en-BM.json",
"Intl.js/locale-data/json/en-BS.json",
"Intl.js/locale-data/json/en-BW.json",
"Intl.js/locale-data/json/en-BZ.json",
"Intl.js/locale-data/json/en-CA.json",
"Intl.js/locale-data/json/en-CC.json",
"Intl.js/locale-data/json/en-CK.json",
"Intl.js/locale-data/json/en-CM.json",
"Intl.js/locale-data/json/en-CX.json",
"Intl.js/locale-data/json/en-DG.json",
"Intl.js/locale-data/json/en-DM.json",
"Intl.js/locale-data/json/en-Dsrt-US.json",
"Intl.js/locale-data/json/en-Dsrt.json",
"Intl.js/locale-data/json/en-ER.json",
"Intl.js/locale-data/json/en-FJ.json",
"Intl.js/locale-data/json/en-FK.json",
"Intl.js/locale-data/json/en-FM.json",
"Intl.js/locale-data/json/en-GB.json",
"Intl.js/locale-data/json/en-GD.json",
"Intl.js/locale-data/json/en-GG.json",
"Intl.js/locale-data/json/en-GH.json",
"Intl.js/locale-data/json/en-GI.json",
"Intl.js/locale-data/json/en-GM.json",
"Intl.js/locale-data/json/en-GU.json",
"Intl.js/locale-data/json/en-GY.json",
"Intl.js/locale-data/json/en-HK.json",
"Intl.js/locale-data/json/en-IE.json",
"Intl.js/locale-data/json/en-IM.json",
"Intl.js/locale-data/json/en-IN.json",
"Intl.js/locale-data/json/en-IO.json",
"Intl.js/locale-data/json/en-JE.json",
"Intl.js/locale-data/json/en-JM.json",
"Intl.js/locale-data/json/en-KE.json",
"Intl.js/locale-data/json/en-KI.json",
"Intl.js/locale-data/json/en-KN.json",
"Intl.js/locale-data/json/en-KY.json",
"Intl.js/locale-data/json/en-LC.json",
"Intl.js/locale-data/json/en-LR.json",
"Intl.js/locale-data/json/en-LS.json",
"Intl.js/locale-data/json/en-MG.json",
"Intl.js/locale-data/json/en-MH.json",
"Intl.js/locale-data/json/en-MO.json",
"Intl.js/locale-data/json/en-MP.json",
"Intl.js/locale-data/json/en-MS.json",
"Intl.js/locale-data/json/en-MT.json",
"Intl.js/locale-data/json/en-MU.json",
"Intl.js/locale-data/json/en-MW.json",
"Intl.js/locale-data/json/en-MY.json",
"Intl.js/locale-data/json/en-NA.json",
"Intl.js/locale-data/json/en-NF.json",
"Intl.js/locale-data/json/en-NG.json",
"Intl.js/locale-data/json/en-NR.json",
"Intl.js/locale-data/json/en-NU.json",
"Intl.js/locale-data/json/en-NZ.json",
"Intl.js/locale-data/json/en-PG.json",
"Intl.js/locale-data/json/en-PH.json",
"Intl.js/locale-data/json/en-PK.json",
"Intl.js/locale-data/json/en-PN.json",
"Intl.js/locale-data/json/en-PR.json",
"Intl.js/locale-data/json/en-PW.json",
"Intl.js/locale-data/json/en-RW.json",
"Intl.js/locale-data/json/en-SB.json",
"Intl.js/locale-data/json/en-SC.json",
"Intl.js/locale-data/json/en-SD.json",
"Intl.js/locale-data/json/en-SG.json",
"Intl.js/locale-data/json/en-SH.json",
"Intl.js/locale-data/json/en-SL.json",
"Intl.js/locale-data/json/en-SS.json",
"Intl.js/locale-data/json/en-SX.json",
"Intl.js/locale-data/json/en-SZ.json",
"Intl.js/locale-data/json/en-TC.json",
"Intl.js/locale-data/json/en-TK.json",
"Intl.js/locale-data/json/en-TO.json",
"Intl.js/locale-data/json/en-TT.json",
"Intl.js/locale-data/json/en-TV.json",
"Intl.js/locale-data/json/en-TZ.json",
"Intl.js/locale-data/json/en-UG.json",
"Intl.js/locale-data/json/en-UM.json",
"Intl.js/locale-data/json/en-US.json",
"Intl.js/locale-data/json/en-VC.json",
"Intl.js/locale-data/json/en-VG.json",
"Intl.js/locale-data/json/en-VI.json",
"Intl.js/locale-data/json/en-VU.json",
"Intl.js/locale-data/json/en-WS.json",
"Intl.js/locale-data/json/en-ZA.json",
"Intl.js/locale-data/json/en-ZM.json",
"Intl.js/locale-data/json/en-ZW.json",
"Intl.js/locale-data/json/en.json",
"Intl.js/locale-data/json/eo-001.json",
"Intl.js/locale-data/json/eo.json",
"Intl.js/locale-data/json/es-419.json",
"Intl.js/locale-data/json/es-AR.json",
"Intl.js/locale-data/json/es-BO.json",
"Intl.js/locale-data/json/es-CL.json",
"Intl.js/locale-data/json/es-CO.json",
"Intl.js/locale-data/json/es-CR.json",
"Intl.js/locale-data/json/es-CU.json",
"Intl.js/locale-data/json/es-DO.json",
"Intl.js/locale-data/json/es-EA.json",
"Intl.js/locale-data/json/es-EC.json",
"Intl.js/locale-data/json/es-ES.json",
"Intl.js/locale-data/json/es-GQ.json",
"Intl.js/locale-data/json/es-GT.json",
"Intl.js/locale-data/json/es-HN.json",
"Intl.js/locale-data/json/es-IC.json",
"Intl.js/locale-data/json/es-MX.json",
"Intl.js/locale-data/json/es-NI.json",
"Intl.js/locale-data/json/es-PA.json",
"Intl.js/locale-data/json/es-PE.json",
"Intl.js/locale-data/json/es-PH.json",
"Intl.js/locale-data/json/es-PR.json",
"Intl.js/locale-data/json/es-PY.json",
"Intl.js/locale-data/json/es-SV.json",
"Intl.js/locale-data/json/es-US.json",
"Intl.js/locale-data/json/es-UY.json",
"Intl.js/locale-data/json/es-VE.json",
"Intl.js/locale-data/json/es.json",
"Intl.js/locale-data/json/et-EE.json",
"Intl.js/locale-data/json/et.json",
"Intl.js/locale-data/json/eu-ES.json",
"Intl.js/locale-data/json/eu.json",
"Intl.js/locale-data/json/ewo-CM.json",
"Intl.js/locale-data/json/ewo.json",
"Intl.js/locale-data/json/fa-AF.json",
"Intl.js/locale-data/json/fa-IR.json",
"Intl.js/locale-data/json/fa.json",
"Intl.js/locale-data/json/ff-CM.json",
"Intl.js/locale-data/json/ff-GN.json",
"Intl.js/locale-data/json/ff-MR.json",
"Intl.js/locale-data/json/ff-SN.json",
"Intl.js/locale-data/json/ff.json",
"Intl.js/locale-data/json/fi-FI.json",
"Intl.js/locale-data/json/fi.json",
"Intl.js/locale-data/json/fil-PH.json",
"Intl.js/locale-data/json/fil.json",
"Intl.js/locale-data/json/fo-FO.json",
"Intl.js/locale-data/json/fo.json",
"Intl.js/locale-data/json/fr-BE.json",
"Intl.js/locale-data/json/fr-BF.json",
"Intl.js/locale-data/json/fr-BI.json",
"Intl.js/locale-data/json/fr-BJ.json",
"Intl.js/locale-data/json/fr-BL.json",
"Intl.js/locale-data/json/fr-CA.json",
"Intl.js/locale-data/json/fr-CD.json",
"Intl.js/locale-data/json/fr-CF.json",
"Intl.js/locale-data/json/fr-CG.json",
"Intl.js/locale-data/json/fr-CH.json",
"Intl.js/locale-data/json/fr-CI.json",
"Intl.js/locale-data/json/fr-CM.json",
"Intl.js/locale-data/json/fr-DJ.json",
"Intl.js/locale-data/json/fr-DZ.json",
"Intl.js/locale-data/json/fr-FR.json",
"Intl.js/locale-data/json/fr-GA.json",
"Intl.js/locale-data/json/fr-GF.json",
"Intl.js/locale-data/json/fr-GN.json",
"Intl.js/locale-data/json/fr-GP.json",
"Intl.js/locale-data/json/fr-GQ.json",
"Intl.js/locale-data/json/fr-HT.json",
"Intl.js/locale-data/json/fr-KM.json",
"Intl.js/locale-data/json/fr-LU.json",
"Intl.js/locale-data/json/fr-MA.json",
"Intl.js/locale-data/json/fr-MC.json",
"Intl.js/locale-data/json/fr-MF.json",
"Intl.js/locale-data/json/fr-MG.json",
"Intl.js/locale-data/json/fr-ML.json",
"Intl.js/locale-data/json/fr-MQ.json",
"Intl.js/locale-data/json/fr-MR.json",
"Intl.js/locale-data/json/fr-MU.json",
"Intl.js/locale-data/json/fr-NC.json",
"Intl.js/locale-data/json/fr-NE.json",
"Intl.js/locale-data/json/fr-PF.json",
"Intl.js/locale-data/json/fr-PM.json",
"Intl.js/locale-data/json/fr-RE.json",
"Intl.js/locale-data/json/fr-RW.json",
"Intl.js/locale-data/json/fr-SC.json",
"Intl.js/locale-data/json/fr-SN.json",
"Intl.js/locale-data/json/fr-SY.json",
"Intl.js/locale-data/json/fr-TD.json",
"Intl.js/locale-data/json/fr-TG.json",
"Intl.js/locale-data/json/fr-TN.json",
"Intl.js/locale-data/json/fr-VU.json",
"Intl.js/locale-data/json/fr-WF.json",
"Intl.js/locale-data/json/fr-YT.json",
"Intl.js/locale-data/json/fr.json",
"Intl.js/locale-data/json/fur-IT.json",
"Intl.js/locale-data/json/fur.json",
"Intl.js/locale-data/json/fy-NL.json",
"Intl.js/locale-data/json/fy.json",
"Intl.js/locale-data/json/ga-IE.json",
"Intl.js/locale-data/json/ga.json",
"Intl.js/locale-data/json/gd-GB.json",
"Intl.js/locale-data/json/gd.json",
"Intl.js/locale-data/json/gl-ES.json",
"Intl.js/locale-data/json/gl.json",
"Intl.js/locale-data/json/gsw-CH.json",
"Intl.js/locale-data/json/gsw-FR.json",
"Intl.js/locale-data/json/gsw-LI.json",
"Intl.js/locale-data/json/gsw.json",
"Intl.js/locale-data/json/gu-IN.json",
"Intl.js/locale-data/json/gu.json",
"Intl.js/locale-data/json/guz-KE.json",
"Intl.js/locale-data/json/guz.json",
"Intl.js/locale-data/json/gv-GB.json",
"Intl.js/locale-data/json/gv-IM.json",
"Intl.js/locale-data/json/gv.json",
"Intl.js/locale-data/json/ha-Latn-GH.json",
"Intl.js/locale-data/json/ha-Latn-NE.json",
"Intl.js/locale-data/json/ha-Latn-NG.json",
"Intl.js/locale-data/json/ha-Latn.json",
"Intl.js/locale-data/json/ha.json",
"Intl.js/locale-data/json/haw-US.json",
"Intl.js/locale-data/json/haw.json",
"Intl.js/locale-data/json/he-IL.json",
"Intl.js/locale-data/json/he.json",
"Intl.js/locale-data/json/hi-IN.json",
"Intl.js/locale-data/json/hi.json",
"Intl.js/locale-data/json/hr-BA.json",
"Intl.js/locale-data/json/hr-HR.json",
"Intl.js/locale-data/json/hr.json",
"Intl.js/locale-data/json/hsb-DE.json",
"Intl.js/locale-data/json/hsb.json",
"Intl.js/locale-data/json/hu-HU.json",
"Intl.js/locale-data/json/hu.json",
"Intl.js/locale-data/json/hy-AM.json",
"Intl.js/locale-data/json/hy.json",
"Intl.js/locale-data/json/ia-FR.json",
"Intl.js/locale-data/json/ia.json",
"Intl.js/locale-data/json/id-ID.json",
"Intl.js/locale-data/json/id.json",
"Intl.js/locale-data/json/ig-NG.json",
"Intl.js/locale-data/json/ig.json",
"Intl.js/locale-data/json/ii-CN.json",
"Intl.js/locale-data/json/ii.json",
"Intl.js/locale-data/json/is-IS.json",
"Intl.js/locale-data/json/is.json",
"Intl.js/locale-data/json/it-CH.json",
"Intl.js/locale-data/json/it-IT.json",
"Intl.js/locale-data/json/it-SM.json",
"Intl.js/locale-data/json/it.json",
"Intl.js/locale-data/json/ja-JP.json",
"Intl.js/locale-data/json/ja.json",
"Intl.js/locale-data/json/jgo-CM.json",
"Intl.js/locale-data/json/jgo.json",
"Intl.js/locale-data/json/jmc-TZ.json",
"Intl.js/locale-data/json/jmc.json",
"Intl.js/locale-data/json/ka-GE.json",
"Intl.js/locale-data/json/ka.json",
"Intl.js/locale-data/json/kab-DZ.json",
"Intl.js/locale-data/json/kab.json",
"Intl.js/locale-data/json/kam-KE.json",
"Intl.js/locale-data/json/kam.json",
"Intl.js/locale-data/json/kde-TZ.json",
"Intl.js/locale-data/json/kde.json",
"Intl.js/locale-data/json/kea-CV.json",
"Intl.js/locale-data/json/kea.json",
"Intl.js/locale-data/json/khq-ML.json",
"Intl.js/locale-data/json/khq.json",
"Intl.js/locale-data/json/ki-KE.json",
"Intl.js/locale-data/json/ki.json",
"Intl.js/locale-data/json/kk-Cyrl-KZ.json",
"Intl.js/locale-data/json/kk-Cyrl.json",
"Intl.js/locale-data/json/kk.json",
"Intl.js/locale-data/json/kkj-CM.json",
"Intl.js/locale-data/json/kkj.json",
"Intl.js/locale-data/json/kl-GL.json",
"Intl.js/locale-data/json/kl.json",
"Intl.js/locale-data/json/kln-KE.json",
"Intl.js/locale-data/json/kln.json",
"Intl.js/locale-data/json/km-KH.json",
"Intl.js/locale-data/json/km.json",
"Intl.js/locale-data/json/kn-IN.json",
"Intl.js/locale-data/json/kn.json",
"Intl.js/locale-data/json/ko-KP.json",
"Intl.js/locale-data/json/ko-KR.json",
"Intl.js/locale-data/json/ko.json",
"Intl.js/locale-data/json/kok-IN.json",
"Intl.js/locale-data/json/kok.json",
"Intl.js/locale-data/json/ks-Arab-IN.json",
"Intl.js/locale-data/json/ks-Arab.json",
"Intl.js/locale-data/json/ks.json",
"Intl.js/locale-data/json/ksb-TZ.json",
"Intl.js/locale-data/json/ksb.json",
"Intl.js/locale-data/json/ksf-CM.json",
"Intl.js/locale-data/json/ksf.json",
"Intl.js/locale-data/json/ksh-DE.json",
"Intl.js/locale-data/json/ksh.json",
"Intl.js/locale-data/json/kw-GB.json",
"Intl.js/locale-data/json/kw.json",
"Intl.js/locale-data/json/ky-Cyrl-KG.json",
"Intl.js/locale-data/json/ky-Cyrl.json",
"Intl.js/locale-data/json/ky-KG.json",
"Intl.js/locale-data/json/ky.json",
"Intl.js/locale-data/json/lag-TZ.json",
"Intl.js/locale-data/json/lag.json",
"Intl.js/locale-data/json/lb-LU.json",
"Intl.js/locale-data/json/lb.json",
"Intl.js/locale-data/json/lg-UG.json",
"Intl.js/locale-data/json/lg.json",
"Intl.js/locale-data/json/lkt-US.json",
"Intl.js/locale-data/json/lkt.json",
"Intl.js/locale-data/json/ln-AO.json",
"Intl.js/locale-data/json/ln-CD.json",
"Intl.js/locale-data/json/ln-CF.json",
"Intl.js/locale-data/json/ln-CG.json",
"Intl.js/locale-data/json/ln.json",
"Intl.js/locale-data/json/lo-LA.json",
"Intl.js/locale-data/json/lo.json",
"Intl.js/locale-data/json/lt-LT.json",
"Intl.js/locale-data/json/lt.json",
"Intl.js/locale-data/json/lu-CD.json",
"Intl.js/locale-data/json/lu.json",
"Intl.js/locale-data/json/luo-KE.json",
"Intl.js/locale-data/json/luo.json",
"Intl.js/locale-data/json/luy-KE.json",
"Intl.js/locale-data/json/luy.json",
"Intl.js/locale-data/json/lv-LV.json",
"Intl.js/locale-data/json/lv.json",
"Intl.js/locale-data/json/mas-KE.json",
"Intl.js/locale-data/json/mas-TZ.json",
"Intl.js/locale-data/json/mas.json",
"Intl.js/locale-data/json/mer-KE.json",
"Intl.js/locale-data/json/mer.json",
"Intl.js/locale-data/json/mfe-MU.json",
"Intl.js/locale-data/json/mfe.json",
"Intl.js/locale-data/json/mg-MG.json",
"Intl.js/locale-data/json/mg.json",
"Intl.js/locale-data/json/mgh-MZ.json",
"Intl.js/locale-data/json/mgh.json",
"Intl.js/locale-data/json/mgo-CM.json",
"Intl.js/locale-data/json/mgo.json",
"Intl.js/locale-data/json/mk-MK.json",
"Intl.js/locale-data/json/mk.json",
"Intl.js/locale-data/json/ml-IN.json",
"Intl.js/locale-data/json/ml.json",
"Intl.js/locale-data/json/mn-Cyrl-MN.json",
"Intl.js/locale-data/json/mn-Cyrl.json",
"Intl.js/locale-data/json/mn.json",
"Intl.js/locale-data/json/mr-IN.json",
"Intl.js/locale-data/json/mr.json",
"Intl.js/locale-data/json/ms-Latn-BN.json",
"Intl.js/locale-data/json/ms-Latn-MY.json",
"Intl.js/locale-data/json/ms-Latn-SG.json",
"Intl.js/locale-data/json/ms-Latn.json",
"Intl.js/locale-data/json/ms.json",
"Intl.js/locale-data/json/mt-MT.json",
"Intl.js/locale-data/json/mt.json",
"Intl.js/locale-data/json/mua-CM.json",
"Intl.js/locale-data/json/mua.json",
"Intl.js/locale-data/json/my-MM.json",
"Intl.js/locale-data/json/my.json",
"Intl.js/locale-data/json/naq-NA.json",
"Intl.js/locale-data/json/naq.json",
"Intl.js/locale-data/json/nb-NO.json",
"Intl.js/locale-data/json/nb-SJ.json",
"Intl.js/locale-data/json/nb.json",
"Intl.js/locale-data/json/nd-ZW.json",
"Intl.js/locale-data/json/nd.json",
"Intl.js/locale-data/json/ne-IN.json",
"Intl.js/locale-data/json/ne-NP.json",
"Intl.js/locale-data/json/ne.json",
"Intl.js/locale-data/json/nl-AW.json",
"Intl.js/locale-data/json/nl-BE.json",
"Intl.js/locale-data/json/nl-BQ.json",
"Intl.js/locale-data/json/nl-CW.json",
"Intl.js/locale-data/json/nl-NL.json",
"Intl.js/locale-data/json/nl-SR.json",
"Intl.js/locale-data/json/nl-SX.json",
"Intl.js/locale-data/json/nl.json",
"Intl.js/locale-data/json/nmg-CM.json",
"Intl.js/locale-data/json/nmg.json",
"Intl.js/locale-data/json/nn-NO.json",
"Intl.js/locale-data/json/nn.json",
"Intl.js/locale-data/json/nnh-CM.json",
"Intl.js/locale-data/json/nnh.json",
"Intl.js/locale-data/json/nr-ZA.json",
"Intl.js/locale-data/json/nr.json",
"Intl.js/locale-data/json/nso-ZA.json",
"Intl.js/locale-data/json/nso.json",
"Intl.js/locale-data/json/nus-SD.json",
"Intl.js/locale-data/json/nus.json",
"Intl.js/locale-data/json/nyn-UG.json",
"Intl.js/locale-data/json/nyn.json",
"Intl.js/locale-data/json/om-ET.json",
"Intl.js/locale-data/json/om-KE.json",
"Intl.js/locale-data/json/om.json",
"Intl.js/locale-data/json/or-IN.json",
"Intl.js/locale-data/json/or.json",
"Intl.js/locale-data/json/os-GE.json",
"Intl.js/locale-data/json/os-RU.json",
"Intl.js/locale-data/json/os.json",
"Intl.js/locale-data/json/pa-Arab-PK.json",
"Intl.js/locale-data/json/pa-Arab.json",
"Intl.js/locale-data/json/pa-Guru-IN.json",
"Intl.js/locale-data/json/pa-Guru.json",
"Intl.js/locale-data/json/pa.json",
"Intl.js/locale-data/json/pl-PL.json",
"Intl.js/locale-data/json/pl.json",
"Intl.js/locale-data/json/ps-AF.json",
"Intl.js/locale-data/json/ps.json",
"Intl.js/locale-data/json/pt-AO.json",
"Intl.js/locale-data/json/pt-BR.json",
"Intl.js/locale-data/json/pt-CV.json",
"Intl.js/locale-data/json/pt-GW.json",
"Intl.js/locale-data/json/pt-MO.json",
"Intl.js/locale-data/json/pt-MZ.json",
"Intl.js/locale-data/json/pt-PT.json",
"Intl.js/locale-data/json/pt-ST.json",
"Intl.js/locale-data/json/pt-TL.json",
"Intl.js/locale-data/json/pt.json",
"Intl.js/locale-data/json/qu-BO.json",
"Intl.js/locale-data/json/qu-EC.json",
"Intl.js/locale-data/json/qu-PE.json",
"Intl.js/locale-data/json/qu.json",
"Intl.js/locale-data/json/rm-CH.json",
"Intl.js/locale-data/json/rm.json",
"Intl.js/locale-data/json/rn-BI.json",
"Intl.js/locale-data/json/rn.json",
"Intl.js/locale-data/json/ro-MD.json",
"Intl.js/locale-data/json/ro-RO.json",
"Intl.js/locale-data/json/ro.json",
"Intl.js/locale-data/json/rof-TZ.json",
"Intl.js/locale-data/json/rof.json",
"Intl.js/locale-data/json/root.json",
"Intl.js/locale-data/json/ru-BY.json",
"Intl.js/locale-data/json/ru-KG.json",
"Intl.js/locale-data/json/ru-KZ.json",
"Intl.js/locale-data/json/ru-MD.json",
"Intl.js/locale-data/json/ru-RU.json",
"Intl.js/locale-data/json/ru-UA.json",
"Intl.js/locale-data/json/ru.json",
"Intl.js/locale-data/json/rw-RW.json",
"Intl.js/locale-data/json/rw.json",
"Intl.js/locale-data/json/rwk-TZ.json",
"Intl.js/locale-data/json/rwk.json",
"Intl.js/locale-data/json/sah-RU.json",
"Intl.js/locale-data/json/sah.json",
"Intl.js/locale-data/json/saq-KE.json",
"Intl.js/locale-data/json/saq.json",
"Intl.js/locale-data/json/sbp-TZ.json",
"Intl.js/locale-data/json/sbp.json",
"Intl.js/locale-data/json/se-FI.json",
"Intl.js/locale-data/json/se-NO.json",
"Intl.js/locale-data/json/se-SE.json",
"Intl.js/locale-data/json/se.json",
"Intl.js/locale-data/json/seh-MZ.json",
"Intl.js/locale-data/json/seh.json",
"Intl.js/locale-data/json/ses-ML.json",
"Intl.js/locale-data/json/ses.json",
"Intl.js/locale-data/json/sg-CF.json",
"Intl.js/locale-data/json/sg.json",
"Intl.js/locale-data/json/shi-Latn-MA.json",
"Intl.js/locale-data/json/shi-Latn.json",
"Intl.js/locale-data/json/shi-Tfng-MA.json",
"Intl.js/locale-data/json/shi-Tfng.json",
"Intl.js/locale-data/json/shi.json",
"Intl.js/locale-data/json/si-LK.json",
"Intl.js/locale-data/json/si.json",
"Intl.js/locale-data/json/sk-SK.json",
"Intl.js/locale-data/json/sk.json",
"Intl.js/locale-data/json/sl-SI.json",
"Intl.js/locale-data/json/sl.json",
"Intl.js/locale-data/json/smn-FI.json",
"Intl.js/locale-data/json/smn.json",
"Intl.js/locale-data/json/sn-ZW.json",
"Intl.js/locale-data/json/sn.json",
"Intl.js/locale-data/json/so-DJ.json",
"Intl.js/locale-data/json/so-ET.json",
"Intl.js/locale-data/json/so-KE.json",
"Intl.js/locale-data/json/so-SO.json",
"Intl.js/locale-data/json/so.json",
"Intl.js/locale-data/json/sq-AL.json",
"Intl.js/locale-data/json/sq-MK.json",
"Intl.js/locale-data/json/sq-XK.json",
"Intl.js/locale-data/json/sq.json",
"Intl.js/locale-data/json/sr-Cyrl-BA.json",
"Intl.js/locale-data/json/sr-Cyrl-ME.json",
"Intl.js/locale-data/json/sr-Cyrl-RS.json",
"Intl.js/locale-data/json/sr-Cyrl-XK.json",
"Intl.js/locale-data/json/sr-Cyrl.json",
"Intl.js/locale-data/json/sr-Latn-BA.json",
"Intl.js/locale-data/json/sr-Latn-ME.json",
"Intl.js/locale-data/json/sr-Latn-RS.json",
"Intl.js/locale-data/json/sr-Latn-XK.json",
"Intl.js/locale-data/json/sr-Latn.json",
"Intl.js/locale-data/json/sr.json",
"Intl.js/locale-data/json/ss-SZ.json",
"Intl.js/locale-data/json/ss-ZA.json",
"Intl.js/locale-data/json/ss.json",
"Intl.js/locale-data/json/ssy-ER.json",
"Intl.js/locale-data/json/ssy.json",
"Intl.js/locale-data/json/st-LS.json",
"Intl.js/locale-data/json/st-ZA.json",
"Intl.js/locale-data/json/st.json",
"Intl.js/locale-data/json/sv-AX.json",
"Intl.js/locale-data/json/sv-FI.json",
"Intl.js/locale-data/json/sv-SE.json",
"Intl.js/locale-data/json/sv.json",
"Intl.js/locale-data/json/sw-KE.json",
"Intl.js/locale-data/json/sw-TZ.json",
"Intl.js/locale-data/json/sw-UG.json",
"Intl.js/locale-data/json/sw.json",
"Intl.js/locale-data/json/swc-CD.json",
"Intl.js/locale-data/json/swc.json",
"Intl.js/locale-data/json/ta-IN.json",
"Intl.js/locale-data/json/ta-LK.json",
"Intl.js/locale-data/json/ta-MY.json",
"Intl.js/locale-data/json/ta-SG.json",
"Intl.js/locale-data/json/ta.json",
"Intl.js/locale-data/json/te-IN.json",
"Intl.js/locale-data/json/te.json",
"Intl.js/locale-data/json/teo-KE.json",
"Intl.js/locale-data/json/teo-UG.json",
"Intl.js/locale-data/json/teo.json",
"Intl.js/locale-data/json/tg-Cyrl-TJ.json",
"Intl.js/locale-data/json/tg-Cyrl.json",
"Intl.js/locale-data/json/tg.json",
"Intl.js/locale-data/json/th-TH.json",
"Intl.js/locale-data/json/th.json",
"Intl.js/locale-data/json/ti-ER.json",
"Intl.js/locale-data/json/ti-ET.json",
"Intl.js/locale-data/json/ti.json",
"Intl.js/locale-data/json/tig-ER.json",
"Intl.js/locale-data/json/tig.json",
"Intl.js/locale-data/json/tn-BW.json",
"Intl.js/locale-data/json/tn-ZA.json",
"Intl.js/locale-data/json/tn.json",
"Intl.js/locale-data/json/to-TO.json",
"Intl.js/locale-data/json/to.json",
"Intl.js/locale-data/json/tr-CY.json",
"Intl.js/locale-data/json/tr-TR.json",
"Intl.js/locale-data/json/tr.json",
"Intl.js/locale-data/json/ts-ZA.json",
"Intl.js/locale-data/json/ts.json",
"Intl.js/locale-data/json/twq-NE.json",
"Intl.js/locale-data/json/twq.json",
"Intl.js/locale-data/json/tzm-Latn-MA.json",
"Intl.js/locale-data/json/tzm-Latn.json",
"Intl.js/locale-data/json/tzm.json",
"Intl.js/locale-data/json/ug-Arab-CN.json",
"Intl.js/locale-data/json/ug-Arab.json",
"Intl.js/locale-data/json/ug.json",
"Intl.js/locale-data/json/uk-UA.json",
"Intl.js/locale-data/json/uk.json",
"Intl.js/locale-data/json/ur-IN.json",
"Intl.js/locale-data/json/ur-PK.json",
"Intl.js/locale-data/json/ur.json",
"Intl.js/locale-data/json/uz-Arab-AF.json",
"Intl.js/locale-data/json/uz-Arab.json",
"Intl.js/locale-data/json/uz-Cyrl-UZ.json",
"Intl.js/locale-data/json/uz-Cyrl.json",
"Intl.js/locale-data/json/uz-Latn-UZ.json",
"Intl.js/locale-data/json/uz-Latn.json",
"Intl.js/locale-data/json/uz.json",
"Intl.js/locale-data/json/vai-Latn-LR.json",
"Intl.js/locale-data/json/vai-Latn.json",
"Intl.js/locale-data/json/vai-Vaii-LR.json",
"Intl.js/locale-data/json/vai-Vaii.json",
"Intl.js/locale-data/json/vai.json",
"Intl.js/locale-data/json/ve-ZA.json",
"Intl.js/locale-data/json/ve.json",
"Intl.js/locale-data/json/vi-VN.json",
"Intl.js/locale-data/json/vi.json",
"Intl.js/locale-data/json/vo-001.json",
"Intl.js/locale-data/json/vo.json",
"Intl.js/locale-data/json/vun-TZ.json",
"Intl.js/locale-data/json/vun.json",
"Intl.js/locale-data/json/wae-CH.json",
"Intl.js/locale-data/json/wae.json",
"Intl.js/locale-data/json/wal-ET.json",
"Intl.js/locale-data/json/wal.json",
"Intl.js/locale-data/json/xh-ZA.json",
"Intl.js/locale-data/json/xh.json",
"Intl.js/locale-data/json/xog-UG.json",
"Intl.js/locale-data/json/xog.json",
"Intl.js/locale-data/json/yav-CM.json",
"Intl.js/locale-data/json/yav.json",
"Intl.js/locale-data/json/yi-001.json",
"Intl.js/locale-data/json/yi.json",
"Intl.js/locale-data/json/yo-BJ.json",
"Intl.js/locale-data/json/yo-NG.json",
"Intl.js/locale-data/json/yo.json",
"Intl.js/locale-data/json/zgh-MA.json",
"Intl.js/locale-data/json/zgh.json",
"Intl.js/locale-data/json/zh-Hans-CN.json",
"Intl.js/locale-data/json/zh-Hans-HK.json",
"Intl.js/locale-data/json/zh-Hans-MO.json",
"Intl.js/locale-data/json/zh-Hans-SG.json",
"Intl.js/locale-data/json/zh-Hans.json",
"Intl.js/locale-data/json/zh-Hant-HK.json",
"Intl.js/locale-data/json/zh-Hant-MO.json",
"Intl.js/locale-data/json/zh-Hant-TW.json",
"Intl.js/locale-data/json/zh-Hant.json",
"Intl.js/locale-data/json/zh.json",
"Intl.js/locale-data/json/zu-ZA.json",
"Intl.js/locale-data/json/zu.json",
];
};
